name: dwtr

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres
    ports:
      - 8080:8080
    restart: always

  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - postgres
    ports:
      - 5432
    restart: always
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge

secrets:
  postgres_db:
    environment: POSTGRES_DB
  postgres_user:
    environment: POSTGRES_USER
  postgres_password:
    environment: POSTGRES_PASSWORD

volumes:
  pgdata: