name: dwtr

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OAUTH2_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      OAUTH2_GOOGLE_REDIRECT_URL: ${OAUTH2_GOOGLE_REDIRECT_URL}
      OAUTH2_GOOGLE_SECRET: ${OAUTH2_GOOGLE_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - postgres
    ports:
      - 8080:8080
    restart: always

  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - pgadmin
      - postgres
    ports:
      - ${POSTGRES_PORT}
    restart: always
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.6.0
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    networks:
      - pgadmin
    ports:
      - 5050:80
    restart: always
    secrets:
      - pgadmin_password
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  pgadmin:
    driver: bridge
  postgres:
    driver: bridge

secrets:
  pgadmin_password:
    environment: PGADMIN_DEFAULT_PASSWORD
  postgres_db:
    environment: POSTGRES_DB
  postgres_user:
    environment: POSTGRES_USER
  postgres_password:
    environment: POSTGRES_PASSWORD

volumes:
  pgadmin:
  pgdata: