name: dwtr

services:
  app:
    build:
      context: .
    depends_on:
      - minio
      - postgres
    environment:
      APP_PORT: ${APP_PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_PERMISSION_NAMESPACE: ${ADMIN_PERMISSION_NAMESPACE}
      ADMIN_PERMISSION_NAME: ${ADMIN_PERMISSION_NAME}

      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      MINIO_URL: http://minio:${MINIO_PORT}/
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      OAUTH2_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      OAUTH2_GOOGLE_REDIRECT_URL: ${OAUTH2_GOOGLE_REDIRECT_URL}
      OAUTH2_GOOGLE_SECRET: ${OAUTH2_GOOGLE_SECRET}

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - minio
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    command: minio server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: :${MINIO_PORT}
      MINIO_CONSOLE_ADDRESS: :${MINIO_CONSOLE_PORT}
    networks:
      - minio
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    restart: always
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  minio:
    driver: bridge
  postgres:
    driver: bridge

secrets:
  postgres_db:
    environment: POSTGRES_DB
  postgres_user:
    environment: POSTGRES_USER
  postgres_password:
    environment: POSTGRES_PASSWORD

volumes:
  minio_data:
  pgdata: