name: Project Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  style-check:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Run scalafmtCheck
        run: sbt scalafmtCheckAll scalafmtSbtCheck

  build-commons:
    name: Compile and run tests for commons
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: commons module
        run: sbt "project commons" compile test

  build-auth:
    name: Compile and run tests for auth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: auth module
        run: sbt "project auth" compile test

  build-permissions:
    name: Compile and run tests for permissions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: permissions module
        run: sbt "project permissions" compile test

  build-aggregator:
    name: Compile and run tests for aggregator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: aggregator module
        run: sbt "project aggregator" compile test

  build-app:
    name: Compile app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: app module
        run: sbt "project app" compile
